kind: ConfigMap
apiVersion: v1
metadata:
  name: moodle
  namespace: 950003-test
data:
  config.php: |
    <?php  // Moodle configuration file

    unset($CFG);
    global $CFG;
    $CFG = new stdClass();

    $CFG->dbtype    = 'mysqli';
    $CFG->dblibrary = 'native';
    $CFG->dbhost    = getenv('DB_HOST');
    $CFG->dbname    = getenv('DB_NAME');
    $CFG->dbuser    = getenv('DB_USER');
    $CFG->dbpass    = getenv('DB_PASSWORD');
    $CFG->prefix    = '';
    $CFG->dboptions = array (
      'dbpersist' => 0,
      'dbport' => 3306,
      'dbsocket' => '',
      'dbcollation' => 'utf8mb4_0900_ai_ci',
    );

    $CFG->wwwroot   = getenv('SITE_URL');
    $CFG->dataroot  = getenv('MOODLE_DATA_PATH');
    $CFG->admin     = 'admin';

    $CFG->directorypermissions = 0777;

    $CFG->sslproxy  = true;

    require_once(__DIR__ . '/lib/setup.php');

    // There is no php closing tag in this file,
    // it is intentional because it prevents trailing whitespace problems!
